# Copyright (c) 2016-2024 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
site_name: spatula
site_url: https://seqscope.github.io/spatula/

# Repository
repo_name: seqscope/spatula
repo_url: https://github.com/seqscope/spatula

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    # - content.code.copy
    # - content.tooltips
    # - navigation.footer
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Install: install.md
  - Tools: 
    - Introduction: tools.md
    - Analysis of Spatial Barcodes:
      - build-sbcds: tools/build_sbcds.md
      - eval-dups-sbcds: tools/eval_dups_sbcds.md
      - combine-sbcds: tools/combine_sbcds.md
      - match-sbcds: tools/match_sbcds.md
    - Analysis of Spatial Gene Expression (SGE): 
      - dge2sge: tools/dge2sge.md
      - subset-sge: tools/subset_sge.md
    - FASTQ Processing: 
      - reformat-fastqs: tools/reformat_fastqs.md
      - custom-demux-fastq: tools/custom_demux_fastq.md
    - Miscellaneous Tools: 
      - draw-xy: tools/draw_xy.md
      - draw-3way: tools/draw_3way.md

markdown_extensions:
  # - abbr
  - attr_list
  # - def_list
  - footnotes
  # - md_in_html
  - toc:
      permalink: true
  ## MathJax expression support
  - pymdownx.arithmatex:
      generic: true
  ## Improved detection of Markup 
  - pymdownx.betterem:
      smart_enable: all
  ## Highight text and define sub- and superscript
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  ## Collapsible blocks
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  # - pymdownx.highlight:
  #     anchor_linenums: true
  #     line_spans: __span
  #     pygments_lang_class: true
  # - pymdownx.inlinehilite
  # - pymdownx.keys
  # - pymdownx.magiclink:
  #     normalize_issue_symbols: true
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # - pymdownx.tasklist:
  #     custom_checkbox: true